version: '3.3'

services:

  postgres:
    image: postgres:latest
    command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres#
      POSTGRES_DB: test
    ports:
      - "5432:5432"

#  mongo:
#    image: mongo:latest
#    ports:
#      - "27017:27017"
